export const CARDS = {
REVERSECARD: '../assets/img/reverseCard.png',
CARD_1:'../assets/img/aladinMonkey.png',
CARD_2:'../assets/img/athenianSmokingMonkey.png',
CARD_3:'../assets/img/blueBandanaMonkey.png',
CARD_4:'../assets/img/blueMarineMonkey.png',
CARD_5:'../assets/img/coinEyesMonkey.png',
CARD_6:'../assets/img/highEyesMonkey.png',
CARD_7:'../assets/img/highHolyMonkey.png',
CARD_8:'../assets/img/jailSmokingMonkey.png',
CARD_9:'../assets/img/karateMonkey.png',
CARD_10:'../assets/img/marineHighEyesMonkey.png',
CARD_11:'../assets/img/marineMonkey.png',
CARD_12:'../assets/img/whiteMarineMonkey.png',
CARD_13:'../assets/img/athenianRobotMonkey.png',
CARD_14:'../assets/img/karate3DMonkey.png',
CARD_15:'../assets/img/smokingRobotMonkey.png',
CARD_16:'../assets/img/sunglassesRobotMonkey.png',
CARD_17:'../assets/img/smokingSunglassesMonkey.png',
}